using device: cuda:0
dt: 0.009999999776482582
[34m[1mwandb[39m[22m: [33mWARNING[39m Found log directory outside of given root_logdir, dropping given root_logdir for event file in /home/drj/workspaces/runs/quad__ppo_continuous_action__1__1717744172
[91m[1m[Error] [carb.windowing-glfw.plugin] GLFW initialization failed.
[91m[1m[Error] [carb.windowing-glfw.plugin] GLFW window creation failed!
[91m[1m[Error] [carb.gym.plugin] Failed to create Window in CreateGymViewerInternal
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
 CREATING ENVIRONMENT
Total robot mass:  1.9399999752640724
 ENVIRONMENT CREATED
num actions:  4
num obs:  13
self.counter: 0
SPS: 9169
SPS: 14444
SPS: 17933
SPS: 20300
SPS: 21294
SPS: 22699
SPS: 23808
SPS: 24811
SPS: 25663
SPS: 26372
SPS: 26798
SPS: 27328
SPS: 27727
SPS: 27618
SPS: 28009
global_step=123392, episodic_return=925.6751708984375
self.counter: 250
SPS: 28350
global_step=131584, episodic_return=995.669921875
global_step=132096, episodic_return=982.5137329101562
SPS: 28662
global_step=140800, episodic_return=1063.6552734375
SPS: 28921
global_step=147968, episodic_return=1122.787841796875
global_step=148480, episodic_return=1108.4998779296875
global_step=148992, episodic_return=1130.9189453125
SPS: 29168
global_step=156160, episodic_return=1177.90234375
global_step=156672, episodic_return=1196.859130859375
global_step=157184, episodic_return=1183.196044921875
SPS: 29383
global_step=164352, episodic_return=1245.3006591796875
global_step=164864, episodic_return=1242.93798828125
global_step=165376, episodic_return=1254.474609375
SPS: 29548
global_step=172544, episodic_return=1314.801025390625
global_step=173056, episodic_return=1295.8255615234375
global_step=173568, episodic_return=1315.91259765625
SPS: 29600
global_step=180736, episodic_return=1367.75439453125
global_step=181248, episodic_return=1374.3121337890625
global_step=181760, episodic_return=1373.8624267578125
SPS: 29776
global_step=188928, episodic_return=1434.12109375
global_step=189440, episodic_return=1442.02099609375
global_step=189952, episodic_return=1436.0147705078125
SPS: 29390
global_step=197120, episodic_return=1495.5054931640625
global_step=197632, episodic_return=1502.4544677734375
global_step=198144, episodic_return=1502.0736083984375
SPS: 29569
global_step=205312, episodic_return=1556.26513671875
global_step=205824, episodic_return=1558.736083984375
global_step=206336, episodic_return=1559.4412841796875
SPS: 29734
global_step=213504, episodic_return=1622.465087890625
global_step=214528, episodic_return=1607.4124755859375
Traceback (most recent call last):
  File "ppo_continuous_action.py", line 405, in <module>
    loss = pg_loss - args.ent_coef * entropy_loss + v_loss * args.vf_coef
KeyboardInterrupt
SPS: 29894
global_step=222208, episodic_return=1682.65234375
global_step=222720, episodic_return=1671.663330078125
SPS: 30026
global_step=229888, episodic_return=1757.51806640625
global_step=230912, episodic_return=1754.022705078125
SPS: 30138
global_step=238080, episodic_return=1820.044921875
SPS: 30223
SPS: 30331
global_step=255488, episodic_return=1942.823974609375
self.counter: 500
SPS: 30400
global_step=262656, episodic_return=858.4658203125
global_step=263680, episodic_return=846.1154174804688
SPS: 30476
global_step=270848, episodic_return=1049.5067138671875
global_step=271360, episodic_return=871.8488159179688
global_step=271872, episodic_return=960.46875
SPS: 30527
global_step=279040, episodic_return=931.1842041015625
global_step=280064, episodic_return=868.8091430664062